### ISSUE TITLE
Packages page is missing community-authored packages

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/kitura.io#139]
https://github.com/crspybits/CredentialsDropbox
https://github.com/jacobvanorder/Kitura-CredentialsTwitter

**Comment by helenmasters** [comment]
@ianpartridge are you happy if I add these to the Credentials tile on packages.html as it seems the logical place to me unless we want to add a new community-authored tile?

**Comment by ianpartridge** [comment]
Yes, the existing credentials tile makes most sense. Perhaps with a "community" label.
