### ISSUE TITLE
Application Metrics for Swift Documentation Outdated

### ISSUE THREAD

**Issue by jonathan-spruce** [IBM-Swift/kitura.io#150]
The documentation on the [Learn - Application Metrics for Swift](https://www.kitura.io/guides/building/metrics.html) page is currently outdated. SwiftMetrics is now already included when using `kitura init`, and adding the code as instructed starts a second SwiftMetrics instance leading to the dashboard displaying multiple versions of each metric (e.g. memory, cpu, etc.):
<img width="1248" alt="screen shot 2018-06-20 at 13 21 38" src="https://user-images.githubusercontent.com/40430178/41768585-90c98b74-7604-11e8-8759-874c47c02ae5.png">

### Environment Details
macOS 10.13.5, Swift 4.2.1, Xcode 9.4.1

### Steps to Reproduce
1) Run `kitura init` to create a new project
2) Follow the steps on the [Learn - Application Metrics for Swift](https://www.kitura.io/guides/building/metrics.html) page to add SwiftMetrics to the project
3) Run the project and access the SwiftMetricsDash from localhost:[port_no]/swiftmetrics-dash
4) Each metrics graph is duplicated multiple times and are incorrectly displayed.

**Comment by ianpartridge** [comment]
I believe this page was designed to help users to add SwiftMetrics to their Kitura app if they _didn't_ start via `kitura init`. So probably we should update the page to make it clear that it's not necessary to follow the instructions if you used the CLI.

**Comment by ddunn2** [comment]
I agree with @ianpartridge 

If a user created their server using the Kitura CLI or the Kitura App (starter project) then these instructions aren't needed. 
But if a user creates their Kitura server using SPM or the Kitura App (Skeleton project) then these instructions are still useful as you'll need to know how to add all the components of Swift Metrics. 

Part of the work I'm doing around the website will involve how we structure our docs, I will definitely take this into consideration during the design of this. 
For the time being Ian's suggestion would work well, Maybe add a  [warning](https://github.com/IBM-Swift/kitura.io/blob/master/CONTRIBUTING.md#notices) at the top of the page stating you don't need to do this if you followed the CLI or starter project instructions.

**Comment by ddunn2** [comment]
PR has been merged for this!
