### ISSUE TITLE
Documentation reference for Learn page. 

### ISSUE THREAD

**Issue by ddunn2** [IBM-Swift/kitura.io#182]
Documentation Structure: 

- **Getting Started**
  - **Setting Up** Prerequisites?
  - **Configuration**: A section on how to configure a Kitura project?
  - **Kitura CLI** (Split this up?)
  - **macOS app**
  - **SPM**
- **Logging**
- **Routing**
  - **What is routing?**
  - **Raw Routing**
   1. Terminology help (i.e. what is response? Request?)
   2. How to implement each route (GET, POST... etc etc)
  - **Codable Routing**
   1. Terminology help (i.e. What is Codable? Why use this routing?)
   2. How to implement each route (GET, POST... etc etc)
- **Middlewares**
  - **What is a Middleware?**
  - **Raw middlewares**
  - **Type-safe middlewares**
- **Monitoring**
- **OpenAPI**
- **Databases**
  - **What are Databases?** Uses?
  - **Swift-Kuery**
  - **ORM**
  - **Plugins** (MySQL, PostgreSQL, SQLite)
  - **CouchDB/Cloudant?**
  - **Redis**
- **Sessions**
  - **What are sessions?** Why would a user need them? Terminology help?
  - **Raw Sessions**
  - **Type Safe sessions (codable)**
- **Authentication**
  - **What is Authentication?** Why would a user need them? Terminology help?
  - **Basic Auth**
  - **JWT Auth**
  - **Facebook, Google Token Auth**
  - **Facebook, Google, App ID: Similar? (Oauth2)**
- **Web Apps**
  - **What is Templating?** Terminology help?
  - **Stencil**
  - **Markdown**
  - **HTML Forms**
- **Deploying a project**
  - **Docker**
  - **Kubernetes**
  - **Cloud Foundry**
- **iOS Client**
  - **KituraKit** Do we need this? Or should it be a part of the deployment section?
<hr>

Currently the docs are a little scattered/unstructured, we should group together our documentation and fill in any doc gaps we have. 

Above is a first draft of a potential documentation reference structure (i.e. The list that would appear down the side of a documentation page, and would allow a user to navigate via links). 

The text in **Bold** with bullet points shows headings and sub headings. The numbered lists show the contents of an individual documentation page.

**Comment by ddunn2** [comment]
Below is a design I've put together of what the docs page could look like. 

![docsver4](https://user-images.githubusercontent.com/25609923/47567172-ba744700-d925-11e8-9db8-b5305d0fd45f.png)

**Comment by sympatheticmoose** [comment]
@ddunn2 design is looking nice and clean, and glad we're starting to look at the taxonomy of the site :) I'm going to share some content strategy materials/exercises with you and @ianpartridge - I think they might help here

**Comment by ianpartridge** [comment]
@sympatheticmoose did you send these?

**Comment by ddunn2** [comment]
@ianpartridge 
He sent them over to me, I'll share them with you as well.
