### ISSUE TITLE
Parsing JSON Posts : about adding SwiftyJSON to Package.swift

### ISSUE THREAD

**Issue by chooco13** [IBM-Swift/kitura.io#22]
Hi :)  
I was trying to [pasing requests](http://www.kitura.io/en/resources/tutorials/parsingrequests.html) tutorials from `kitura.io`  

I don't understand why this expression should be in there  
"Import SwiftyJSON by adding it to your Package.swift file".  
that make me more confused

I thought 'I should add extra dependency?'.  So I added dependency in Package.swift.
but it make build errors.

because SwiftyJSON already cloned by just adding 'Kitura.git'.

So "Import SwiftyJSON by adding it to your Package.swift file" should be in there?

**Comment by ianpartridge** [comment]
Hi, which version of Kitura are you using, and which version of SwiftyJSON did you add to your `Package.swift`?

**Comment by chooco13** [comment]
I set my `Package.swift` as [Getting Started](http://www.kitura.io/en/starter/gettingstarted.html) did

> import PackageDescription
> 
> let package = Package(
>     name: "kitura-example",
>     dependencies: [
>         .Package(url: "https://github.com/IBM-Swift/Kitura.git", majorVersion: 1, minor: 2)
>     ])

and I build the project.

> [chooco13@mbp ~/project/kitura-example]$ swift build
> Cloning https://github.com/IBM-Swift/Kitura.git
> HEAD is now at 072b853 Regenerated the API documentation
> Resolved version: 1.2.0
> Cloning https://github.com/IBM-Swift/Kitura-net.git
> HEAD is now at 01cfbc0 Merge pull request #145 from IBM-Swift/issue_877
> Resolved version: 1.2.1
> Cloning https://github.com/IBM-Swift/LoggerAPI.git
> HEAD is now at c64ce64 Merge pull request #16 from IBM-Swift/issue_832
> Resolved version: 1.1.0
> Cloning https://github.com/IBM-Swift/BlueSocket.git
> HEAD is now at d97739b Update Travis build badge.  Was using the wrong one.
> Resolved version: 0.12.2
> Cloning https://github.com/IBM-Swift/CCurl.git
> HEAD is now at 3cfb752 Add header callback helper function (#9)
> Resolved version: 0.2.3
> Cloning https://github.com/IBM-Swift/BlueSSLService.git
> HEAD is now at 5a3c1e8 Update Travis build badge.  Was using the wrong one.
> Resolved version: 0.12.4
> Cloning https://github.com/IBM-Swift/SwiftyJSON.git
> HEAD is now at 64b0910 Merge pull request #27 from IBM-Swift/issue_846
> Resolved version: 15.0.1
> Cloning https://github.com/IBM-Swift/Kitura-TemplateEngine.git
> HEAD is now at 4fe7829 Support Swift 3.0.1 (#9)
> Resolved version: 1.1.0
> Compile Swift Module 'Socket' (3 sources)
> Compile Swift Module 'LoggerAPI' (1 sources)
> Compile Swift Module 'KituraTemplateEngine' (1 sources)
> Compile Swift Module 'SwiftyJSON' (2 sources)
> Compile Swift Module 'SSLService' (1 sources)
> Compile CHTTPParser utils.c
> Compile CHTTPParser http_parser.c
> Linking CHTTPParser
> Compile Swift Module 'KituraNet' (34 sources)
> Compile Swift Module 'Kitura' (41 sources)
> Compile Swift Module 'kitura_example' (1 sources)
> Linking ./.build/debug/kitura-example

You can see. they automatically clone SwiftJSON by just adding `Kitura.git` to my dependency.

if I add SwiftyJSON to current Package.swift, they have conflicts
because there is SwiftyJSON already.

So What I want to say is  
Why
> Import SwiftyJSON by adding it to your Package.swift file and by adding import SwiftyJSON to the top of your file.
  
not Just

> Import SwiftyJSON by adding import SwiftyJSON to the top of your file.

**Comment by ianpartridge** [comment]
Which version of SwiftyJSON did you add to your `Package.swift`? If you add version 15 (the same as version 1.2 of Kitura specifies), then it should work.

I think it's best practice to import the version of a dependency that your code requires. That way, if an update to Kitura changes the version of SwiftyJSON it uses, SPM will notify you when you build, so you can update your code to the same version.

**Comment by chooco13** [comment]
Oh, I understand.

Can you add that explanation shortly to [Tutorial](http://www.kitura.io/en/resources/tutorials/parsingrequests.html) for beginner?
because swift beginner like me, didn't know that

**Comment by ianpartridge** [comment]
Thanks - I've added a sentence to this effect!
