### ISSUE TITLE
Feedback on Routing - Codable Routing

### ISSUE THREAD

**Issue by helenmasters** [IBM-Swift/kitura.io#250]
- [x] Prerequisites "This section will inform you of the minimum you need to have setup to follow this guide." can we simplify this wording? "This section defines what you need to setup to follow this guide."

- [x] Prerequisites: I don't like the phrase "highly recommend" in this context. If you really need a word in addition to recommend I'd prefer "strongly recommend" but wouldn't "recommend" be suitable?

- [x] Step 1: Having the hint about "If you created your project using Kitura CLI or the Kitura macOS app then your project structure may be different."  before anything else is confusing as I'd not even read the "Open your main.swift file" comment yet.  ? Having the Getting Started with SPM using main.swift and Kitura CLI and the macOS app using Application.swift  is going to give us ongoing problems/confusion - I have to wonder if it is worth changing the Getting Started with SPM to use Application.swift and main.swift?

- [x] main.swift needs backticks

- [x] "The handling is defined by the handler parameter. Which is a block of code that will be executed in reponse to the request." These two sentences need joining with a comma. reponse -> response

- [x] Step 2 - you have in the text `postHandler` both backtick'd and not. This needs to be consistent (same in step 3).

- [x] In "Step 2 - Define the handler" why don't we combine the first two statements into "If we try to build the project now it will fail to compile, because the `postHandler` hasn't been defined."

- [x] "The result should look similar to this:" the result sounds like we've run something which we're not doing at this stage, how about "The code should now look similar to:" or "The code should now look as follows:"

- [x] Step 3 "Book is a custom Swift type that we haven't defined yet. So lets go ahead and define it." why don't we combine these to read more easily "Book is a custom Swift type that we haven't defined yet, so let's go ahead and define it:"

- [x] Within Step 3: Encoders and Decoders do these need capitals?

- [ ] In Step 3 we talk about the tuple of type (Book?, RequestError?) it seems strange that we mention Book and then how to define it but never mention RequestError again?

- [ ] In step 3 I think the following text "Simply put, `Book` is a struct that conforms to Codable. Codable is a Swift protocol that provides Encoders and Decoders to convert to and from JSON." should be with the definition of the `Book` struct as it is odd having it at the bottom under the entire piece of code. This may mean a little rewording within the second part of step 3.

- [x] Step 4 Test the POST route
In the hint box there is a reference to an OpenAPI guide which doesn't link anywhere...?
"Kitura has support for OpenAPI which makes testing Codable routes easy and provides a UI for testing." the wording here could be snappier how about "Kitura has support for OpenAPI which allows easy end to end testing of Codable routes". 
The first reference to OpenAPI should link to the OpenAPI website.

- [ ] Step 4 Test the POST route
"With the project now compiling we can start the server." I think this should be "Now that your project compiles, start the server: " followed by the command to do this!  You can't assume people know how to do this.

- [ ] Step 4 contd... Tell people what they should see when the server is successfully running... then you can put something like "We are going to use cURL (link out to the cURL site just in case people haven't got it installed) to send a request to our server." then you can have "Open a terminal window and enter the following:"

- [ ] Step 4 contd... "We have just posted data, now we need to be able to retrieve the data." -> "Now we have posted data, next we will retrieve the data."

- [ ] Step 5 This step is dependent on other previous steps being completed, which may confuse users given we've presented a list of links above as though all the options are not dependent on being run in order.

- [ ] Step 5 "Registering a GET route is very similar to registering a POST route."

- [ ] Step 5 "Just like before we now need to define the handler" -> "As before, we need to define the handler."

- [ ] I think you need to combine some of the text in step 5 into a paragraph as it's too broken up to read easily as it is.

- [ ] Does Dictonary need a capital D or should it be back tick'd?

- [ ] I think the hint needs to be more like "Note: it is not good practice to use a dictionary to store data on the server, we are using a dictionary here for the sake of simplicity, a better solution would be to use a database. Learn how to do this in our database guide."  database guide needs to be a link.

- [ ] There is no explanation of what
`let books = bookstore.map({ $0.value })
  completion(books, nil)`
within the `getAllHandler` does - I think we need to add some.

- [ ] "Now we can restart our server to test our new endpoint." again we should explain how to do this.

- [ ] "Which makes sense as we haven't stored anything on our server yet." -> "This is an empty dictionary because we haven't stored anything on our server yet."

- [ ] Step 6: "Database section" here "Database guide" above - the wording needs standardizing and it should be a link. Perhaps the wording is better as "We will look at storing and retrieving data in more detail in the database guide."

- [ ] Step 6 postHandler needs backticks.

- [ ] Step 6 We/you "You can modify the postHandler to store the posted book"... more explanation needed here... by adding the book to the bookstore dictionary ...? (as the dictionary was defined in step 5 which is a fair distance away now!)

- [ ] resart your server?

- [ ] and use cURL to post the data to the server...?

- [ ] "Followed by" is a little terse, how about "Now we/you can retrieve the data that was posted:"

- [ ] "Again..." -> "We have quickly demonstrated storing and retrieving data from the server. However, dictionaries are not a practical way for an application to store data, they are used here only to demonstrate Codable routing." Do we need this wording twice?

- [ ] Step 7 QueryParams needs backticks.

- [ ] We need to decide whether to refer to query parameters or QueryParams as reading QueryParams in text doesn't enhance readability here. We also need a section explaining what QueryParams are maybe in the What is routing? section which we could link out to from here, as it's not at all clear at the start of step 7 what we're about to do or why.

- [ ] I don't like reading comments which are embedded in the code as we've done in step 7, not in a guide anyway.  Can we not tag these lines with numbers and explain what those lines are doing in a piece of text?

- [ ] "Finally we just need to register a new GET route using the getSingleQuery handler we just created:" -> "Finally, we need to register a new GET route, to use the `getSingleQuery` handler we just created:"

- [ ] At the end of step 7 it would be nice to actually describe how to run something to demonstrate the code in action (as we have done this for the previous steps). The same is true for steps 8 and 9.

- [ ] Step 8 as in step 7 we should say what we're doing and why. 

"Like before we first need to create a type that conforms to the QueryParams protocol:" -> "First we need to create a type that conforms to the QueryParams protocol:"

- [ ] "Then we create our handler":  "Next" is a better starter than "then"

- [ ] "Then we can filter our data using the query provide:" - this doesn't make sense.

- [ ] Step 9 "Next what if we want to search all books that are of a certain price?" -> "What if we want to search our bookstore by price? We may want to find all the books priced between £5 and £10, or only books that are less than £10."

- [ ] First, we need to define a type that conforms to the QueryParams protocol: - again why?

- [ ] "Now we can query our books based on a range of price". -> Now we can query our books based on a price range." More explanation needed here. TODO needs removing. 

- [ ] I find it confusing that the headings at the top of the file don't always match the step names which they link you to.

- [ ] The following curl command in Test the POST route (step 4) doesn't work - it needs double quotes around "" the word Fantasy:

curl -X POST \
  http://localhost:8080/books \
  -H 'content-type: application/json' \
  -d '{
    "id": 0,
    "title": "A Game of Thrones",
    "price": 14.99,
    "genre": Fantasy
}'

- [ ] `bookstore[book.id] = book` doesn't compile in step 6: it does if changed to `bookstore[String(book.id)] this may/may not be the correct way of fixing it.

- [ ] The curl command in step 6 needs Fantasy double quoting as per above 

- [ ] please can you remove the % from the end of the curl command example output

- [ ] The code below doesn't compile as `QueryParams` isn't in the packages which have been imported in step 7:
`public struct TitleQuery: QueryParams {
  let title: String
}`

- [ ] Create a basic GET single route doesn't link anywhere. There are no learn instructions for this. (I found this when following the "Create a GET SINGLE route with QueryParams" as I was checking that the handler name `getSingleQuery` hadn't already been used.)

- [ ] Step 7 doesn't compile as there is a public struct called TitleQuery which we then refer to as BookQuery. I suggest we change all refs here to TitleQuery.

- [ ] Step 7 still doesn't compile. "Value of tuple type '(key: String, value: Book)' has no member 'title'"... please can you work on steps 7-9 and let me know when it's ready for re-review.

**Comment by Andrew-Lees11** [comment]
I'm closing this issue since the comments have either been addressed or are not relevant due to changes.
