### ISSUE TITLE
Feedback on Routing - Raw routing

### ISSUE THREAD

**Issue by helenmasters** [IBM-Swift/kitura.io#252]

**Comment by helenmasters** [comment]
- [ ] express should have a capital E? ...also would it make more sense to say "the Express framework for Node.js"?

- [ ] "Raw routing is based on express where the route handlers are called with RouterRequest and RouterResponse objects with which to handle the client request and build the response, along with a next completion handler."  how about...

"Raw routing is based on the Express framework for Node.js where the route handlers are called with `RouterRequest` and `RouterResponse` objects, which respectively handle the client request and build the response, along with a `next` completion handler.

**Comment by Andrew-Lees11** [comment]
I'm going to close this issue since the feeback has all been implemented into the guide.
