### ISSUE TITLE
Guide: Migrate "Enabling SSL/TLS on your Kitura server"

### ISSUE THREAD

**Issue by Andrew-Lees11** [IBM-Swift/kitura.io#283]
We have an existing guide for how to enable HTTPS on a kitura server [here](https://www.kitura.io/guides/building/ssl.html). This is pretty useful guide and should be migrated over to the new guides (Possibly into a new utilities section)

**Comment by ddunn2** [comment]
@Andrew-Lees11 Where are you planning to add this guide? 

We currently do not have a 'utilities' section, nor can we easily add one at the moment. 
I have plans to add a new section for guides/information that won't fit into the current flow but we don't have it yet. 

For now I'd recommend not adding this guide, it's still available to users via the old docs page if they require it. But leave this issue open so we know to migrate it in the future.

**Comment by ianpartridge** [comment]
I think this would fit pretty naturally as part of the Deployment section.

**Comment by Andrew-Lees11** [comment]
I agree this could go in deployment. I think it is quite an important guide and would like to migrate it over so I am working on that at the moment (Since the base guide exists in the old docs). If any section gets to large we could look at creating a new one.

**Comment by ddunn2** [comment]
Yeah we can add it to deployment for now then, once we have the scope for adding a new section we can move it to there. 

The only section at risk of being to large is `Getting Started` and in the original layout, `Getting Satrted` had a configuration section which probably could have included this.

**Comment by ianpartridge** [comment]
I think Deployment should be the long-term home. It's the natural place people will look for info about TLS.

**Comment by ddunn2** [comment]
@ianpartridge natural place based on what? 

TLS/SSL information typically falls under Security, Settings or Configuration. You could argue that only users wanting to deploy may wish to use TLS/SSL, unless for example; they are simply playing around with/learning Kitura or creating a Web Application they don't want to deploy. In which case Deployment wouldn't be the place I'd look for information about Security. 

Either way, for now we can place it under Deployment and we can decide what to do with it later.

**Comment by ianpartridge** [comment]
Deciding whether to use TLS is a deployment decision.

**Comment by ddunn2** [comment]
I feel it's a security decision and I think we should adhere to what users would expect. 

Apple keeps their docs around SSL under Security, as do many other frameworks. 

We should also follow this trend going forward so there's no confusion on where to find this information.

**Comment by ianpartridge** [comment]
> Apple keeps their docs around SSL under Security, as do many other frameworks.

Can you provide links please?

**Comment by ddunn2** [comment]
Apple - https://developer.apple.com/documentation/security/secure_transport)
Django - https://docs.djangoproject.com/en/2.2/topics/security/#ssl-https)
Express - https://expressjs.com/en/advanced/best-practice-security.html#use-tls)
Rails - https://guides.rubyonrails.org/security.html & https://guides.rubyonrails.org/configuring.html

There's a few links, I did do research before starting to design the new website layout and by extension the new side list for the docs.

**Comment by ianpartridge** [comment]
Thanks for the links!

I think the difference here is that none of those links are guides on how to enable TLS in those frameworks.  As we have designed the Learn section as an end to end flow the question we need to ask ourselves is "when in the process of following these guides would the user consider whether they require TLS?"  And the answer is deployment. Why? Because that's when the user is deciding whether to use Cloud Foundry / k8s etc. And if they're using k8s they probably don't want TLS on their Kitura app because the TLS will likely be terminated at Ingress. If they're using CF they have [similar considerations to make](https://docs.cloudfoundry.org/adminguide/securing-traffic.html#ssl_options).

Now, there is definitely value in "security best practices" document like Express have, but I don't currently see how that would form part of the flow we've designed at the moment.  It would have to stand alone somehow, like the "Kitura architecture best practices" doc we've discussed previously.

Hope that makes my thinking clearer.

**Comment by ddunn2** [comment]
Thanks for adding some clarity :) 

I think whether they instruct a user how to enable TLS on those frameworks or not is irrelavant, it's where you'd look to find out about the TLS options available. In some of the cases in the links, they recommend using an external tool whereas we provide that option for you. The example we currently use in our TLS guides has nothing to do with Deploying to K8s or CF, it's simply a Hello World example that you can view via https.

Now I definitely agree with thinking about what the user would want as that is what is most important. The guides are an end-to-end flow but they also need to cater for users to enter the docs at any point and work through a section they need. Not everyone will want to follow the docs end-to-end so we should ensure that information is available in a logical place. 

The new layout I'm working on does have a section for Security, as Security is such an important concept which alot of people care about and as such probably should be it's own section. 

I don't seem to recall the discussion about `Kitura architecture best practices` but I also agree we should have something like that. 

As for the current flow, it's a little more coupled than I originally planned for it be. They should flow in a way that also allows them to also stand alone, which they currently do not but I've been talking to Helen about ways to resolve that.

**Comment by ianpartridge** [comment]
What else are you imagining will go in the Security section?

**Comment by ddunn2** [comment]
I haven't got a plan for that yet. 

I first need to research what is typically found in Security, and what users typically would want to know about security when developing a Kitura Server. 

With the former I can draw up a proposal, but the latter will come from asking our users.

**Comment by ianpartridge** [comment]
OK thanks. @Andrew-Lees11 - for now TLS can go in Deployment.  In future we can rethink once @ddunn2 has a proposal for a Security section.  Thanks!
