### ISSUE TITLE
Fix: bullet/list styling

### ISSUE THREAD

**Issue by helenmasters** [IBM-Swift/kitura.io#304]
Items which need fixing:
- [ ] Step 3 in the [Helium Logger guide](https://www.kitura.io/docs/logging/helium-logger.html)
- [ ] Protocol flow in [OAuth 2.0 with Facebook/Google](https://www/kitura.io/docs/authentication/fb-google-oauth2.html)
- [ ] List of routes in [OAuth 2.0 with Facebook/Google](https://www/kitura.io/docs/authentication/fb-google-oauth2.html)
- [ ] Project file structure in [Style Guide](https://www.kitura.io/docs/getting-started/style-guide.html)
- [ ] Database plugin lists in [What is a Database?](https://www.kitura.io/docs/databases/databases.html)
- [ ] Authentication types in [What is Authentication?](https://www.kitura.io/docs/authentication/authentication.html)
- [ ] List of templating engines [What is Templating?](https://www.kitura.io/docs/templating/templating.html) 
- [ ] Features of TLS [Enabling SSL/TLS](https://www.kitura.io/docs/deploying/ssl.html)
- [ ] [Authentication with JWT](http://www.kitura.io/docs/authentication/jwt-auth.html)

**Comment by Andrew-Lees11** [comment]
Closing since this was fixed in #346
