### ISSUE TITLE
Fix: move the Book model out of the Style Guide 

### ISSUE THREAD

**Issue by helenmasters** [IBM-Swift/kitura.io#309]
The Book model is referred to throughout the guides, however, it is currently in the Style Guide which doesn't feel like the right home for it.

The suggestion is to move it into the routing pages and then in the individual guides refer to the requirement for a "codable model", which could be a Book model, and then link to the Book model definition the first time it is required in the example, rather than link to it from all the prereq sections.

**Comment by Andrew-Lees11** [comment]
Closing since this mas moved in pr #379 which has now been merged.
