### ISSUE TITLE
Guide walkthrough: Authentication pages

### ISSUE THREAD

**Issue by wbittles** [IBM-Swift/kitura.io#363]

**Comment by wbittles** [comment]
Step 1: Define the authentication middleware
To add basic authentication to our server, we need to add Kitura-CredentialsHTTP to our dependencies.
Other guides point to a nice general dependencies page, however this link points directly to the github repository and the README doesn't provide details of how to add dependencies.

touch Sources/Application/Middlewares/MyBasicAuth.swift this fails on linux because the Middlewares directory isn't created by default.

**Comment by wbittles** [comment]
JSON Web Tokens 

when following the Elliptic Curve Digital Signature Algorithm (ECDSA) there is a compile error, JWTRoutes.swift:12:47: error: type 'App' has no member 'signer'
        let signedJWT = try myJWT.sign(using: App.signer)

App.signer should be App.jwtSigner

**Comment by wbittles** [comment]
Step 6: Test the JWT creation

The CURL post returns a string without a CR/LF , not the JWT string returned below with the extra 'w' at the end.

eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJleHAiOjE1NTk4MzQ1MzcuMjQ4OTczLCJpc3MiOiJLaXR1cmEiLCJzdWIiOiJKb2UgQmxvZ2dzIn0.HHHJJliIlYwjfSO27hqjNP4BdDKblZtxx16H6W5gzlnvORpmfmQU_-KLKaEEHovoOvztSUsxxwbJc_dll5gEQAw

**Comment by wbittles** [comment]
Before the sentence below we are offered the choice of 3 encryption schemes and the sample code changes accordingly, yet here we only provide a completed file for a single choice.

Congratulations! We have just created a JWT single sign on system using a Kitura Server. Your completed JWTRoutes.swift file for HS256 should look as follows:

**Comment by wbittles** [comment]
The google OAuth sample fails to work as expected with the redirect failing with error 

[2019-06-07T15:13:23.488+01:00] [ERROR] [ClientRequest.swift:531 end(close:)] ClientRequest error. Failed to parse response. Error=Parsed fewer bytes than were passed to the HTTP parser

still under investigation

**Comment by Andrew-Lees11** [comment]
I have raised a pull request to address these comments:
- There is now a [pull request](https://github.com/IBM-Swift/Kitura-CredentialsHTTP/pull/60) to credentialsHTTP adding a usage guide which is being pointed at
- I have added a line for creating the middlewares folder if it doesn't already exist
- We do need a raw routing Basic authentication guide and issue #132 exists to track this
- JWT typo causing compile error has been fixed
- We decided to keep the single complete example at the end for simplicity. When the website changed the toggle system will probably change as well so this can be addressed then
- Oauth2 failure is tracked in the issue you linked
