### ISSUE TITLE
Guide walkthrough: Web Application pages

### ISSUE THREAD

**Issue by helenmasters** [IBM-Swift/kitura.io#364]

**Comment by wbittles** [comment]
Step 1: Add KituraMarkdown to the Kitura App
 Below the line let router = Router() we will add:
 router.add(templateEngine: KituraMarkdown())

Adding the above line causes compile errors all the code needed should reside in the postInit() function
which I have successfully tested

**Comment by wbittles** [comment]
Kitura is capable of having numerous template engines registered to a single instance of a router.
Kitura then provides APIs to select a default template engine to use. 

A link to the docs for the provided APIs would be nice

**Comment by helenmasters** [comment]
Billy has completed the guide walkthrough now I need to digest the feedback and make appropriate changes to kitura.io.
