### ISSUE TITLE
Kitura OAuth 2.0 google guide does not work

### ISSUE THREAD

**Issue by wbittles** [IBM-Swift/kitura.io#374]
When running the Google OAuth 2.0 sample from the Authentication guide the code does not work as expected. The initial log on via google appears to work in that the Google login isn't  presented again and the following redirection  url is produced , note the code=4

http://localhost:8080/oauth2/google?code=4/ZgGihvsLud3xZke37eplRP1YpMfTyzax7tPWt0MjnSLsVxr6H1xzTGEDoRgFrKic-fei8NFVyaS7bH08Jl-Eadg&scope=profile+https://www.googleapis.com/auth/userinfo.profile

However the user is not authenticated and is not granted access to the protected route or  the logout route.

The console produced the following error
 [2019-06-11T11:20:25.694+01:00] [ERROR] [ClientRequest.swift:531 end(close:)] ClientRequest error. Failed to parse response. Error=Parsed fewer bytes than were passed to the HTTP parser

**Comment by Andrew-Lees11** [comment]
After some investigation, it turns out this is a bug in curl 7.58 which is brought in by default for Ubuntu 18.04.  
This bug means that chunked encoding is called twice as described [here](https://github.com/curl/curl/issues/2303). This was fixed in 7.59 however we would like this to be fixed in the Ubuntu release so that Kitura-net can handle chunked encoding.

**Comment by wbittles** [comment]
I've opened the following bug against Ubuntu 
https://bugs.launchpad.net/ubuntu/+source/hdf5/+bug/1833198

**Comment by Andrew-Lees11** [comment]
I am going to close this issue since it is not related to kitura.io but is instead an issue with curl and Ubuntu 18.04. Hopefully they will fix the bug swiftly

**Comment by wbittles** [comment]
I have tested this by building curl-7.65.1 and and linking it to the Kitura OAuth application which resolved the issue.
