### ISSUE TITLE
Update KituraMarkdown guide 

### ISSUE THREAD

**Issue by ddunn2** [IBM-Swift/kitura.io#384]
We should update the KituraMarkdown guide to demonstrate how to use the [render(from: String, pageTemplate: String](https://github.com/IBM-Swift/Kitura-Markdown/blob/master/Sources/KituraMarkdown/KituraMarkdown.swift#L205) API so users can provide an HTML wrapper for their Markdown snippets.

**Comment by ianpartridge** [comment]
This is inspired by https://github.com/IBM-Swift/Kitura-Markdown/issues/25 :)

**Comment by djones6** [comment]
#385 is now merged.
