### ISSUE TITLE
Guide: Web Sockets

### ISSUE THREAD

**Issue by helenmasters** [IBM-Swift/kitura.io#394]
There is no guide for Web Sockets and how to use them.

@pushkarnk and @ianpartridge given that we're working on the Kitura "I'm safe" lab which uses WebSockets can we factor in a WebSocket guide as part of that work?

**Comment by ianpartridge** [comment]
@djones6 could Cameron perhaps take this one?

**Comment by djones6** [comment]
@CameronMcWilliam As the lab uses NIO, we need to consider whether the guide should cover websockets for Net and NIO - sync up with @pushkarnk on this

**Comment by djones6** [comment]
Guide has been written but needs a review - @CameronMcWilliam please could you ask @harish1992 to do that?

**Comment by djones6** [comment]
https://github.com/IBM-Swift/kitura.io/pull/401 has been merged.
