### ISSUE TITLE
Missing steps in documentation for Swift Server Generator

### ISSUE THREAD

**Issue by dingwilson** [IBM-Swift/kitura.io#40]
# Missing steps in documentation for Swift Server Generator
The [getting started documentation](http://www.kitura.io/en/starter/generator/getting_started.html) is missing a few steps for the creation process.

The flow should be:
```
? What's the name of your application?
? Enter the name of the directory to contain the project:
? Select type of project:
? Select capabilities: (Press <space> to select, <a> to toggle all, <i> to inver
se selection)
? Select data store:
```

![Type of Project](https://cloud.githubusercontent.com/assets/8827679/24489093/05ec4daa-14e1-11e7-96eb-58bbf26105ed.jpeg)

![Capabilities](https://cloud.githubusercontent.com/assets/8827679/24489116/23b0aa3e-14e1-11e7-89ac-73e90fb8e9a0.jpeg)

**Comment by tunniclm** [comment]
@dingwilson The documentation has not been updated for version 2.0.0 of the generator yet. The changes are in progress here: https://github.com/IBM-Swift/kitura.io/tree/swiftserver_2

**Comment by tunniclm** [comment]
I think we have a reasonable set of updated docs now, so I have creates PR #41.
Just need to do a final check tomorrow with those who have contributed to make sure there's no edits pending, then it should be ready to merge.

**Comment by tunniclm** [comment]
Updates have been merged and are now live on http://www.kitura.io/en/starter/generator.html
