### ISSUE TITLE
Decide on tutorials to be displayed on new docs page and add descriptions

### ISSUE THREAD

**Issue by helenmasters** [IBM-Swift/kitura.io#429]
There is space for 4 tutorials on the new docs page which 4 would we like displayed, currently we are linking to:

[FoodTracker Backend](https://github.com/IBM/FoodTrackerBackend)
[ToDo Backend](https://github.com/IBM/ToDoBackend)
[The OpenAPI Spec and Kitura: Getting Started](https://www.raywenderlich.com/1030830-the-openapi-spec-and-kitura-getting-started)
[Kitura Stencil Tutorial: How to make Websites with Swift](https://www.raywenderlich.com/1032630-kitura-stencil-tutorial-how-to-make-websites-with-swift)

These also all need short custom descriptions as the descriptions for all 4 are wrong at the moment.

**Comment by helenmasters** [comment]
@ianpartridge please can you list which 4 tutorials are the most recent and useful regarding Kitura on Swift so that we can get this page updated?

**Comment by ianpartridge** [comment]
Let's drop FoodTracker and replace it with https://github.com/IBM/Kitura-SOS-Workshop
