### ISSUE TITLE
Update guides for Swift 4

### ISSUE THREAD

**Issue by youming-lin** [IBM-Swift/kitura.io#56]
https://github.com/IBM-Swift/Kitura/issues/1156#issuecomment-333896228

**Comment by helenmasters** [comment]
@youming-lin please can you close this now, as the Getting Started has been rewritten and no longer contains this information.  Swift 4 updates have been made across the kitura.io site now and the Package.swift here http://www.kitura.io/en/starter/generator/package_swift.html has been updated accordingly.
