### ISSUE TITLE
Extra horizontal space in tutorials page on mobile screens

### ISSUE THREAD

**Issue by imjog** [IBM-Swift/kitura.io#70]
when we swipe left in tutorials page on mobile screen there is little blank space due to over size of todo-image.

**Screenshot:**
![screen shot 2017-11-03 at 18 56 27](https://user-images.githubusercontent.com/20956124/32376210-1eb07ce0-c0ca-11e7-8e82-f2c50d13d5ff.png)

**It should be look like this :**
![screen shot 2017-11-03 at 18 55 45](https://user-images.githubusercontent.com/20956124/32376237-3594a97c-c0ca-11e7-90e6-78e80ac061d1.png)

**Comment by helenmasters** [comment]
Thanks for raising this issue @imjog, when I looked on a mobile screen you are quite correct the display does have unsightly extra white space.
