### ISSUE TITLE
Remove `defer { next() }` from tutorials

### ISSUE THREAD

**Issue by svanimpe** [IBM-Swift/kitura.io#79]
Deferring `next()` causes the response to be sent before error handlers get called (if an error is thrown). I've asked about this on Slack several months ago and got confirmation that this is indeed an anti-pattern. I believe it was @shmuelk who confirmed this, but I am not sure.

Unfortunately, many developers new to Kitura still use it, most likely because it is still used on kitura.io, for example in: http://www.kitura.io/en/resources/tutorials/templating.html

**Comment by helenmasters** [comment]
@svanimpe thanks for raising this issue, I've made some changes, please check that they address your concerns. Please do raise any further issues which you notice and also feel free to send any suggestions for additional documentation my way.

**Comment by ianpartridge** [comment]
Closing as resolved.
