### ISSUE TITLE
Slack / Github icon alignment on FHD screen (Android/Chrome)

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/kitura.io#86]
On my Android mobile, the appearance of the new icons on Kitura.io is crowded toward the centre, as if there is too much fixed padding to their right:

![screenshot_20180219-112108](https://user-images.githubusercontent.com/17850918/36375649-ff6d3d94-1567-11e8-95f0-8f9595bcf4ce.png)

This is viewing in Chrome on a full HD screen (1080 x 1920) in portrait.

Additionally, whilst the Slack icon is nice and clear, the Github and StackOverflow icons are fuzzy (low resolution) when zoomed beyond the default level.

**Comment by helenmasters** [comment]
@KyeMaloy97 assigning this to you as I know that you've been working in this area.

**Comment by djones6** [comment]
The fix in #105 resolves this - tested on FHD (1080p) and 720p screens.
